# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: ya78yrc8n4w3984
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    show_sql: false
    hibernate.ddl-auto: update
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    ROOT: INFO

jsop-cfg:
  agent: Mozilla/5.0 (Windows; U; WindowsNT5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

indexing-settings:
  sites:
    - url: https://sendel.ru
      name: Konstantin Shibkov
#    - url: https://www.lenta.ru
#      name: Лента.ру
    - url: https://academynsk.ru/
      name: Салон красоты
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://motovar.ru/
#      name: Продажа запчастей и расходных материалов
#    - url: https://ipfran.ru/
#      name: ipfran.ru
